### ISSUE TITLE
inventories and short games

### ISSUE THREAD

**Issue by AvondaleZPR** [dricholm/guess-the-hero#33]
pls add a check when hero's  inventory is empty or game lasted less then 25 minutes!

**Comment by dricholm** [comment]
Hello @AvondaleZPR,
Thanks for opening an issue and sorry for the late response as I noticed it just now.
Do you mean that matches with only 25+ minutes and heroes who have items should be eligible for guessing, right? That sounds good to me. I will take a look at it, but can't promise a completion date yet.

**Comment by dricholm** [comment]
I have done some rework (in #35) so the player with the highest net worth will be selected for guessing so it should reduce players with poor inventories.
As for match duration, I don't think it's possible to set a duration when querying the API unfortunately. Could only fetch each match individually and check it but I don't think that's a good workaround.
